### ISSUE TITLE
Wiki?

### ISSUE THREAD

**Issue by PaperVb64** [Prakxo/ac-decomp#317]
Could you prehaps move the mds in the docs folder to a Wiki prehaps? It's just inaccessible to have them in a folder directly in the repo, where the common person (such as myself, to an extent) wouldn't think to look. It also makes things more manageable.

**Comment by Prakxo** [comment]
They're labeled in the readme as "quick guides"

**Comment by PaperVb64** [comment]
I know, but wouldn't it be easier to just have a tab for them, opposed to links that you have to scroll down to find?

**Comment by PaperVb64** [comment]
Alright, just a suggestion. By the way, what do the guides mean by the tools folder???

**Comment by Cuyler36** [comment]
> Alright, just a suggestion. By the way, what do the guides mean by the tools folder???

The tools folder in the repository. When you clone the repo you'll get everything including the tools folder. Make sure to follow every step in the readme to properly set up the repo. The guides are included in the repo rather than the Wiki page so they can be viewed offline.
