### ISSUE TITLE
Using Ghidxx

### ISSUE THREAD

**Issue by nensondubois** [Prakxo/ac-decomp#361]
Using NSGAY software for reverse-engineering videogames, including Animal Crossing is gross and unethical. All of your work should be discredited and removed.

As a software developer, I find it highly unethical and will not support videogame de-compilation projects using such software.
Seriously, github needs to approve repositories and not just let anyone dump projects without vetting.

**Comment by thebxzr** [comment]
i'm gonna be really honest nobody cares

**Comment by nensondubois** [comment]
And that's the problem. "No one cares". That's not a good enough answer, honestly, this is why the world has a lot of problems.

**Comment by thebxzr** [comment]
if you have enough free time to care about people who are passionate about decompiling and figuring out the intricate clockwork of a comfort game many of them have been playing for over 20 years, then you need to find a hobby

also, the issues tab is for programming issues inside the repo itself, so this is technically a misuse of the issues tab

**Comment by thebxzr** [comment]
also thanks for the compliment, i know i'm shitty <3

**Comment by MisterSheeple** [comment]
Ghidxx? Ghidxx isn't any software I've ever heard of.
